[project]
name = "pyseasters"
version = "1.0.0-alpha.1"
description = "Python package to handle data in the SEASTERS project."
authors = [{ name = "Quentin Desmet", email = "desmetque@gmail.com" }]

[project.optional-dependencies]
dev = [
  "isort",
  "black",
  "flake8",
  "flake8-pyproject",
  "mypy",
  "types-PyYAML",
  "pytest",
  "pytest-cov",
]
docs = [
  "sphinx",
  "sphinx-rtd-theme",
  "myst-parser",
  "sphinx-autodoc2",
]

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88

[tool.flake8]
ignore = ["E501"]
exclude = ["examples/*"]
per-file-ignores = """
  */__init__.py: F401
"""

[tool.mypy]
exclude = '^examples/'

[tool.pytest.ini_options]
addopts = "-v --cov=pyseasters --cov-report=term-missing"
